# Generated by Django 5.0.6 on 2024-06-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_admin', '0003_remove_choice_question_remove_question_survey_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True},
        ),
    ]
