# Generated by Django 5.0.6 on 2024-07-03 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_admin', '0007_survey_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
