# Generated by Django 5.0.6 on 2024-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_admin', '0008_survey_end_time_survey_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('radio', 'Radio'), ('select', 'Select'), ('integer', 'Integer'), ('rating', 'Rating')], default='text', max_length=10),
        ),
    ]
