# Generated by Django 5.0.6 on 2024-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_admin', '0009_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
